###
# Example pod with containers for using KSQL on Kubernetes. Not for production.
#
# Before you run:
# - Note the bootstrap servers are `my-confluent-oss-cp-kafka:9092`. You may need to change this with your own connection strings
#
# Run the pod:
#   $ kubectl apply -f examples/ksql-demo.yaml
#
# Run KSQL CLI:
#   $ kubectl exec -it ksql-demo --container ksql -- /bin/bash ksql
#   ksql> list topics ;
#   ksql> print 'pageviews';
#
#   Then create any query: https://docs.confluent.io/current/ksql/docs/tutorials/basics-docker.html#create-a-stream-and-table
#
###
apiVersion: v1
kind: Pod
metadata:
  name: ksql-cli
  namespace: default
spec:
  containers:
  - name: ksql-cli
    image: confluentinc/cp-ksql-cli:5.0.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"